### ISSUE TITLE
Support for analyzers

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder-multilingual#2]
Add support for language-aware analyzers and sorters.

Configuration example:

```yaml
settings:
  supported-langs:
    cs:
      text:     # adds options for the "text" type field
        analyzer: czech
      sort:    # adds options for the "sort" field. If not present, not generated
        type: icu_collation_keyword
      keyword:   # adds options for the keyword field. if not present, not generated
```

This would generate the following mapping

```yaml
title_cs:
  analyzer: czech
  type: text
  fields:
    keyword:
      type: keyword
      # ...
    sort:
      type: icu_collation_keyword
      index: false
      language: cs
```
