### ISSUE TITLE
Support for other types of multilingual strings

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder-multilingual#4]
Apart from the current `type=multilingual` (we are keeping it), additional "internationalised" strings would be useful.

**Note**: the syntax below is just a suggestion. 

1. A single string tagged with a language

```yaml
keyword:
  type: langString
```

It would generate the following schema:

```json
{
"keyword": {
  "type": "object",
  "properties": {
    "lang": {"type": "string", "enum": [languages]}
    "value" {"type": "string"}
  },
  "required": ["lang", "value"]
} 
}
```

2. Inheriting from a string tagged with a language

```yaml
title:
  oarepo:use: langString
  properties:
    titleType:
      type: string
```

would generate

```json
{
"keyword": {
  "type": "object",
  "properties": {
    "lang": {"type": "string", "enum": [languages]}
    "value":  {"type": "string"},
    "titleType": {"type": "string"}
  },
  "required": ["lang", "value"]
} 
}
```

3. A single-language string with no languages defined (but still should be put to field_[lang], field_sort_[lang] for all "important" languages)

```yaml
title:
  type: fulltext
  oarepo:multilingual:
    i18n: true
    sortable: true
```

4. Extensions to all the language types above that would allow to rename the fields:

```yaml
additionalTitle:
  oarepo:use: langString
  properties:
    titleType:
      type: string
  oarepo:multilingual:
    lang-field: lang
    value-field: title 
```
